//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeReviewUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeReviewUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: Code Review for {0} - {1}.
        /// </summary>
        public static string Label_ActionCodeReview {
            get {
                return ResourceManager.GetString("Label_ActionCodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action : Code Review Comments for {0} - {1}.
        /// </summary>
        public static string Label_ActionCodeReviewComments {
            get {
                return ResourceManager.GetString("Label_ActionCodeReviewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added/Changed Tests.
        /// </summary>
        public static string Label_AddedChangedTests {
            get {
                return ResourceManager.GetString("Label_AddedChangedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Patch....
        /// </summary>
        public static string Label_ApplyPatch {
            get {
                return ResourceManager.GetString("Label_ApplyPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Solutions (Debug/Release) Building.
        /// </summary>
        public static string Label_AreSolutionsBuilding {
            get {
                return ResourceManager.GetString("Label_AreSolutionsBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Outlook Email Message.
        /// </summary>
        public static string Label_CannotCreateEmailMsg {
            get {
                return ResourceManager.GetString("Label_CannotCreateEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string Label_CheckAll {
            get {
                return ResourceManager.GetString("Label_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates....
        /// </summary>
        public static string Label_CheckForUpdates {
            get {
                return ResourceManager.GetString("Label_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Comments.
        /// </summary>
        public static string Label_CheckinComments {
            get {
                return ResourceManager.GetString("Label_CheckinComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Comments Preview.
        /// </summary>
        public static string Label_CheckinCommentsPreview {
            get {
                return ResourceManager.GetString("Label_CheckinCommentsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeReviewCommentsUtility.
        /// </summary>
        public static string Label_CodeCommitCommentsUtility {
            get {
                return ResourceManager.GetString("Label_CodeCommitCommentsUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Review Utility.
        /// </summary>
        public static string Label_CodeReviewUtility {
            get {
                return ResourceManager.GetString("Label_CodeReviewUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit....
        /// </summary>
        public static string Label_Commit {
            get {
                return ResourceManager.GetString("Label_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Path.
        /// </summary>
        public static string Label_CommitPath {
            get {
                return ResourceManager.GetString("Label_CommitPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare....
        /// </summary>
        public static string Label_Compare {
            get {
                return ResourceManager.GetString("Label_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Label_Copy {
            get {
                return ResourceManager.GetString("Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue: [TODO - explain the problem]{0}
        ///Analysis: [TODO - what is the analysis? where is the problem?]{0}
        ///Solution: [TODO - what is the proposed solution, if there were multiple explain this and explain why you have chosen this solution]{0}.
        /// </summary>
        public static string Label_CreateCodeReviewBody {
            get {
                return ResourceManager.GetString("Label_CreateCodeReviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Code Review Utility.
        /// </summary>
        public static string Label_CreateCodeReviewUtility {
            get {
                return ResourceManager.GetString("Label_CreateCodeReviewUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the cause? .
        /// </summary>
        public static string Label_Cue_Cuase {
            get {
                return ResourceManager.GetString("Label_Cue_Cuase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR or PR Desciption/Heading/Brief description of the problem (or change to be implemented)].
        /// </summary>
        public static string Label_Cue_Description {
            get {
                return ResourceManager.GetString("Label_Cue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR or PR number.
        /// </summary>
        public static string Label_Cue_Document_Number {
            get {
                return ResourceManager.GetString("Label_Cue_Document_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite::TestCaseName (if test case is not added/modified, why not?).
        /// </summary>
        public static string Label_Cue_SuiteTestCaseName {
            get {
                return ResourceManager.GetString("Label_Cue_SuiteTestCaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Suite names (if not run, why not?).
        /// </summary>
        public static string Label_Cue_TestSuiteNames {
            get {
                return ResourceManager.GetString("Label_Cue_TestSuiteNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do All Tests Pass.
        /// </summary>
        public static string Label_DoAllTestsPass {
            get {
                return ResourceManager.GetString("Label_DoAllTestsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Changes.
        /// </summary>
        public static string Label_DocumentationChanges {
            get {
                return ResourceManager.GetString("Label_DocumentationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to commit [double click on a file to see the difference(s)].
        /// </summary>
        public static string Label_DoubleClickToSeeDiff {
            get {
                return ResourceManager.GetString("Label_DoubleClickToSeeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comparer specified (Go To Settings).
        /// </summary>
        public static string Label_Error_NoComparer {
            get {
                return ResourceManager.GetString("Label_Error_NoComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Label_Files {
            get {
                return ResourceManager.GetString("Label_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string Label_Heading {
            get {
                return ResourceManager.GetString("Label_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacted Teams.
        /// </summary>
        public static string Label_ImpactedTeams {
            get {
                return ResourceManager.GetString("Label_ImpactedTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Changes.
        /// </summary>
        public static string Label_InstallationChanges {
            get {
                return ResourceManager.GetString("Label_InstallationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string Label_Menu_About {
            get {
                return ResourceManager.GetString("Label_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Label_Menu_Close {
            get {
                return ResourceManager.GetString("Label_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Label_Menu_File {
            get {
                return ResourceManager.GetString("Label_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Label_Menu_Help {
            get {
                return ResourceManager.GetString("Label_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Label_Menu_New {
            get {
                return ResourceManager.GetString("Label_Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Label_Menu_Open {
            get {
                return ResourceManager.GetString("Label_Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Label_Menu_Settings {
            get {
                return ResourceManager.GetString("Label_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Label_Menu_Tools {
            get {
                return ResourceManager.GetString("Label_Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Label_Ok {
            get {
                return ResourceManager.GetString("Label_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubVersion and/or TortoiseSVN is not Installed!
        ///Required Software:
        ///- SubVersion Client	http://www.sliksvn.com/en/download
        ///- Tortoise SVN 	http://tortoisesvn.net/downloads.html.
        /// </summary>
        public static string Label_PreReqSoftware {
            get {
                return ResourceManager.GetString("Label_PreReqSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Label_Preview {
            get {
                return ResourceManager.GetString("Label_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem/Change.
        /// </summary>
        public static string Label_ProblemChange {
            get {
                return ResourceManager.GetString("Label_ProblemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Review Utility.
        /// </summary>
        public static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme Changes.
        /// </summary>
        public static string Label_ReadmeChanges {
            get {
                return ResourceManager.GetString("Label_ReadmeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason/Cause.
        /// </summary>
        public static string Label_ReasonCause {
            get {
                return ResourceManager.GetString("Label_ReasonCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Label_Revert {
            get {
                return ResourceManager.GetString("Label_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the fix/changes made in the task{0}{1}{0}{0}Code review comments:{0}1.	[Comments]{0}2.	[Comments]{0}{0}Unaddressed Code review comments (if any):.
        /// </summary>
        public static string Label_ReviewCommitBody {
            get {
                return ResourceManager.GetString("Label_ReviewCommitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Details.
        /// </summary>
        public static string Label_ReviewDetails {
            get {
                return ResourceManager.GetString("Label_ReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer(s).
        /// </summary>
        public static string Label_Reviewers {
            get {
                return ResourceManager.GetString("Label_Reviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files selected, {1} files in total.
        /// </summary>
        public static string Label_SelectionOverview {
            get {
                return ResourceManager.GetString("Label_SelectionOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action for opening Review Task: &quot;{0}&quot;.
        /// </summary>
        public static string Label_SelectOpeningAction {
            get {
                return ResourceManager.GetString("Label_SelectOpeningAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send....
        /// </summary>
        public static string Label_Send {
            get {
                return ResourceManager.GetString("Label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send via Office Outlook.
        /// </summary>
        public static string Label_SendViaOfficeOutlook {
            get {
                return ResourceManager.GetString("Label_SendViaOfficeOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show At Startup.
        /// </summary>
        public static string Label_ShowAtStartup {
            get {
                return ResourceManager.GetString("Label_ShowAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist....
        /// </summary>
        public static string Label_ShowCheckList {
            get {
                return ResourceManager.GetString("Label_ShowCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log....
        /// </summary>
        public static string Label_ShowLog {
            get {
                return ResourceManager.GetString("Label_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Unversioned Files.
        /// </summary>
        public static string Label_ShowUnversionedFiles {
            get {
                return ResourceManager.GetString("Label_ShowUnversionedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string Label_Solution {
            get {
                return ResourceManager.GetString("Label_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder.
        /// </summary>
        public static string Label_SourceFolder {
            get {
                return ResourceManager.GetString("Label_SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send via Outlook.
        /// </summary>
        public static string Label_StoreOrSendViaOfficeOutlook {
            get {
                return ResourceManager.GetString("Label_StoreOrSendViaOfficeOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVN.
        /// </summary>
        public static string Label_SVN {
            get {
                return ResourceManager.GetString("Label_SVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Label_Tab_Commit {
            get {
                return ResourceManager.GetString("Label_Tab_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Label_Tab_Review {
            get {
                return ResourceManager.GetString("Label_Tab_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id.
        /// </summary>
        public static string Label_TaskId {
            get {
                return ResourceManager.GetString("Label_TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        public static string Label_TaskType {
            get {
                return ResourceManager.GetString("Label_TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests run.
        /// </summary>
        public static string Label_TestsRun {
            get {
                return ResourceManager.GetString("Label_TestsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Review Comments Utility.
        /// </summary>
        public static string Label_Title_CodeReviewCommentsUtility {
            get {
                return ResourceManager.GetString("Label_Title_CodeReviewCommentsUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ToDo].
        /// </summary>
        public static string Label_ToDo {
            get {
                return ResourceManager.GetString("Label_ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Tests.
        /// </summary>
        public static string Label_UnitTests {
            get {
                return ResourceManager.GetString("Label_UnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknow&gt;.
        /// </summary>
        public static string Label_Unknow {
            get {
                return ResourceManager.GetString("Label_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View...
        /// </summary>
        public static string Label_View {
            get {
                return ResourceManager.GetString("Label_View", resourceCulture);
            }
        }
    }
}
